# Generated by Django 4.2.3 on 2023-07-25 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inpimg', '0005_country_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='country',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
