# Generated by Django 4.2.3 on 2023-07-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inpimg', '0006_remove_person_country_delete_country_delete_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
